### ISSUE TITLE
Change videos in the videos in the Biennale App

### ISSUE THREAD

**Issue by LAAP** [ThomasLengeling/MultifoldDisplay#2]
Hi @ThomasLengeling ,

Can you teach us how to play with the App and change videos?

**Comment by ThomasLengeling** [comment]
We can schedule a zoom call next week so that I teach you how to use the app in more detail. If you need to use change the videos now we can have a zoom call today or you can check the instructions of use under the readme section.

The videos have to be with the h.264 codec.

https://github.com/ThomasLengeling/MultifoldDisplay#instructions-use
